language: python
python:
- 3.4
- 3.5
- 3.6
install:
- pip install tox-travis
script:
- tox
# Ensure changelog was written:
- git diff --name-only "${TRAVIS_COMMIT_RANGE}${TRAVIS_TAG}" | grep docs/changes.rst
- '[[ "$TRAVIS_TAG" = "" ]] || grep -i "to be released" docs/changes.rst'
